package com.powerrich;

public class JobEntity
{
	private String JOB_NAME;
	private String TRANSFER_JOB_DEL_STEP_NAME;
	private String TRANSFER_JOB_DEL_STEP_FILE_PATH;
	private String TRANSFER_JOB_SYNC_DATA_STEP_NAME;
	private String TRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH;
	private String TRANSFER_JOB_UPDATE_BASE_STEP_NAME;
	private String TRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH;
	private String JOB_INTERVAL_SECONDS = "0";
	private String JOB_INTERVAL_MINUTES = "0";
	private String LOG_DB_IP;
	private String LOG_DB_TYPE;
	private String LOG_DB_NAME;
	private String LOG_DB_PORT;
	private String LOG_DB_USERNAME;
	private String LOG_DB_ENCREPTED_PASSWORD;
	private String LOG_DB_TABLE;
	
	public String getJOB_NAME() {
		return JOB_NAME;
	}
	public void setJOB_NAME(String jOB_NAME) {
		JOB_NAME = jOB_NAME;
	}
	public String getTRANSFER_JOB_DEL_STEP_NAME() {
		return TRANSFER_JOB_DEL_STEP_NAME;
	}
	public void setTRANSFER_JOB_DEL_STEP_NAME(String tRANSFER_JOB_DEL_STEP_NAME) {
		TRANSFER_JOB_DEL_STEP_NAME = tRANSFER_JOB_DEL_STEP_NAME;
	}
	public String getTRANSFER_JOB_DEL_STEP_FILE_PATH() {
		return TRANSFER_JOB_DEL_STEP_FILE_PATH;
	}
	public void setTRANSFER_JOB_DEL_STEP_FILE_PATH(String tRANSFER_JOB_DEL_STEP_FILE_PATH) {
		TRANSFER_JOB_DEL_STEP_FILE_PATH = tRANSFER_JOB_DEL_STEP_FILE_PATH;
	}
	public String getTRANSFER_JOB_SYNC_DATA_STEP_NAME() {
		return TRANSFER_JOB_SYNC_DATA_STEP_NAME;
	}
	public void setTRANSFER_JOB_SYNC_DATA_STEP_NAME(String tRANSFER_JOB_SYNC_DATA_STEP_NAME) {
		TRANSFER_JOB_SYNC_DATA_STEP_NAME = tRANSFER_JOB_SYNC_DATA_STEP_NAME;
	}
	public String getTRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH() {
		return TRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH;
	}
	public void setTRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH(String tRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH) {
		TRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH = tRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH;
	}
	public String getTRANSFER_JOB_UPDATE_BASE_STEP_NAME() {
		return TRANSFER_JOB_UPDATE_BASE_STEP_NAME;
	}
	public void setTRANSFER_JOB_UPDATE_BASE_STEP_NAME(String tRANSFER_JOB_UPDATE_BASE_STEP_NAME) {
		TRANSFER_JOB_UPDATE_BASE_STEP_NAME = tRANSFER_JOB_UPDATE_BASE_STEP_NAME;
	}
	public String getTRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH() {
		return TRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH;
	}
	public void setTRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH(String tRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH) {
		TRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH = tRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH;
	}
	public String getJOB_INTERVAL_SECONDS() {
		return JOB_INTERVAL_SECONDS;
	}
	public void setJOB_INTERVAL_SECONDS(String jOB_INTERVAL_SECONDS) {
		JOB_INTERVAL_SECONDS = jOB_INTERVAL_SECONDS;
	}
	public String getJOB_INTERVAL_MINUTES() {
		return JOB_INTERVAL_MINUTES;
	}
	public void setJOB_INTERVAL_MINUTES(String jOB_INTERVAL_MINUTES) {
		JOB_INTERVAL_MINUTES = jOB_INTERVAL_MINUTES;
	}
	public String getLOG_DB_IP() {
		return LOG_DB_IP;
	}
	public void setLOG_DB_IP(String lOG_DB_IP) {
		LOG_DB_IP = lOG_DB_IP;
	}
	public String getLOG_DB_TYPE() {
		return LOG_DB_TYPE;
	}
	public void setLOG_DB_TYPE(String lOG_DB_TYPE) {
		LOG_DB_TYPE = lOG_DB_TYPE;
	}
	public String getLOG_DB_NAME() {
		return LOG_DB_NAME;
	}
	public void setLOG_DB_NAME(String lOG_DB_NAME) {
		LOG_DB_NAME = lOG_DB_NAME;
	}
	public String getLOG_DB_PORT() {
		return LOG_DB_PORT;
	}
	public void setLOG_DB_PORT(String lOG_DB_PORT) {
		LOG_DB_PORT = lOG_DB_PORT;
	}
	public String getLOG_DB_USERNAME() {
		return LOG_DB_USERNAME;
	}
	public void setLOG_DB_USERNAME(String lOG_DB_USERNAME) {
		LOG_DB_USERNAME = lOG_DB_USERNAME;
	}
	public String getLOG_DB_ENCREPTED_PASSWORD() {
		return LOG_DB_ENCREPTED_PASSWORD;
	}
	public void setLOG_DB_ENCREPTED_PASSWORD(String lOG_DB_ENCREPTED_PASSWORD) {
		LOG_DB_ENCREPTED_PASSWORD = lOG_DB_ENCREPTED_PASSWORD;
	}
	public String getLOG_DB_TABLE() {
		return LOG_DB_TABLE;
	}
	public void setLOG_DB_TABLE(String lOG_DB_TABLE) {
		LOG_DB_TABLE = lOG_DB_TABLE;
	}
	
}
