package com.powerrich;

public class JobEntity
{
	private String JOB_NAME;
	private String TRANSFER_JOB_DEL_STEP_NAME;
	private String TRANSFER_JOB_DEL_STEP_FILE_PATH;
	private String TRANSFER_JOB_SYNC_DATA_STEP_NAME;
	private String TRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH;
	private String TRANSFER_JOB_UPDATE_BASE_STEP_NAME;
	private String TRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH;
	private String JOB_INTERVAL_SECONDS = "0";
	private String JOB_INTERVAL_MINUTES = "0";
	public String getJOB_NAME() {
		return JOB_NAME;
	}
	public void setJOB_NAME(String jOB_NAME) {
		JOB_NAME = jOB_NAME;
	}
	public String getTRANSFER_JOB_DEL_STEP_NAME() {
		return TRANSFER_JOB_DEL_STEP_NAME;
	}
	public void setTRANSFER_JOB_DEL_STEP_NAME(String tRANSFER_JOB_DEL_STEP_NAME) {
		TRANSFER_JOB_DEL_STEP_NAME = tRANSFER_JOB_DEL_STEP_NAME;
	}
	public String getTRANSFER_JOB_DEL_STEP_FILE_PATH() {
		return TRANSFER_JOB_DEL_STEP_FILE_PATH;
	}
	public void setTRANSFER_JOB_DEL_STEP_FILE_PATH(String tRANSFER_JOB_DEL_STEP_FILE_PATH) {
		TRANSFER_JOB_DEL_STEP_FILE_PATH = tRANSFER_JOB_DEL_STEP_FILE_PATH;
	}
	public String getTRANSFER_JOB_SYNC_DATA_STEP_NAME() {
		return TRANSFER_JOB_SYNC_DATA_STEP_NAME;
	}
	public void setTRANSFER_JOB_SYNC_DATA_STEP_NAME(String tRANSFER_JOB_SYNC_DATA_STEP_NAME) {
		TRANSFER_JOB_SYNC_DATA_STEP_NAME = tRANSFER_JOB_SYNC_DATA_STEP_NAME;
	}
	public String getTRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH() {
		return TRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH;
	}
	public void setTRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH(String tRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH) {
		TRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH = tRANSFER_JOB_SYNC_DATA_STEP_FILE_PATH;
	}
	public String getTRANSFER_JOB_UPDATE_BASE_STEP_NAME() {
		return TRANSFER_JOB_UPDATE_BASE_STEP_NAME;
	}
	public void setTRANSFER_JOB_UPDATE_BASE_STEP_NAME(String tRANSFER_JOB_UPDATE_BASE_STEP_NAME) {
		TRANSFER_JOB_UPDATE_BASE_STEP_NAME = tRANSFER_JOB_UPDATE_BASE_STEP_NAME;
	}
	public String getTRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH() {
		return TRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH;
	}
	public void setTRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH(String tRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH) {
		TRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH = tRANSFER_JOB_UPDATE_BASE_STEP_FILE_PATH;
	}
	public String getJOB_INTERVAL_SECONDS() {
		return JOB_INTERVAL_SECONDS;
	}
	public void setJOB_INTERVAL_SECONDS(String jOB_INTERVAL_SECONDS) {
		JOB_INTERVAL_SECONDS = jOB_INTERVAL_SECONDS;
	}
	public String getJOB_INTERVAL_MINUTES() {
		return JOB_INTERVAL_MINUTES;
	}
	public void setJOB_INTERVAL_MINUTES(String jOB_INTERVAL_MINUTES) {
		JOB_INTERVAL_MINUTES = jOB_INTERVAL_MINUTES;
	}
	
	
}
